name: CICD for serverless
run-name: ${{github.actor}} is doing CICD for serverless

on:
    push:
        branches: [ main,"*" ]

jobs:
    pre-deploy:
        runs-on: ubuntu-latest
        steps:
            - run: echo " The Job is auto tiggered by a ${{github.actor}} event."

    install-dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo code
              uses: actions/checkout@v3
            - name: Run installation of dependencies commands
              run: npm install

    unit-testing:
        runs-on: ubuntu-latest
        steps:
         - name: Check out repo code
           uses: actions/checkout@v3
         - name: Run installation of dependencies commands
           run: npm install
         - name: Run unit testing command
           run: npm test