name: CICD for serverless
run-name: ${{github.actor}} is doing CICD for serverless

on:
    push:
        branches: [ main,"*" ]

jobs:
    pre-deploy:
        runs-on: ubuntu-latest
        steps:
            - run: echo " The Job is auto tiggered by a ${{github.actor}}" event.""